### ISSUE TITLE
Android 8.0 系统监听异常

### ISSUE THREAD

**Issue by Kong-xyZ** [sollian/BottomSheetDialog#1]
KeyboardObserver.onGlobalLayout()这个方法在软键盘隐藏时，没有调用，从而onVisibilityChange这个监听异常。

**Comment by sollian** [comment]
抱歉，刚看到，我复现一下

**Comment by sollian** [comment]
我使用MI6 8.0系统的，无法复现。请问你用的什么手机？

让PanelFragment继承PanelInputDialogFragment也无法正常运行吗？

**Comment by Kong-xyZ** [comment]
在Nokia6(2017)上面Android 8.1系统，运行是没有问题，只是监听会有问题，继承于你写的PanelInputDialogFragment2就会有这个问题

**Comment by sollian** [comment]
手头确实没有这个手机，用模拟器试了一下8.1的系统，没有问题。只能暂时记下了。多谢反馈！

**Comment by Kong-xyZ** [comment]
也有可能是我的页面太过于复杂的原因
